### ISSUE TITLE
Remove empty classes

### ISSUE THREAD

**Issue by AbnerSquared** [AbnerSquared/Orikivo.Classic#1]
The removal of all empty classes in this repository is needed to help clean this mess of code up.

**Comment by imabhinavagarwal** [comment]
Hi @AbnerSquared 
If this issue is open I would like to work on it.. Please let me know
Thanks

**Comment by AbnerSquared** [comment]
@imabhinavagarwal Sorry about that. It was resolved earlier already and I forgot to close it. I'll be opening more issues later on, if that helps any.
