### ISSUE TITLE
Remove redundant constructors

### ISSUE THREAD

**Issue by AbnerSquared** [AbnerSquared/Orikivo.Classic#4]
All classes should not have an empty constructor.

An example is show below on what a redundant constructor looks like:
```cs
public class Class()
{
}
```

The constructor should only be removed if it explicitly states that it is a public constructor.

**Comment by SaulEiros** [comment]
Hi! Can I give you a hand with this?

**Comment by AbnerSquared** [comment]
Go for it! Send a pull request when you're ready. :)

**Comment by SaulEiros** [comment]
Thanks, Sure!

**Comment by SaulEiros** [comment]
Hi! I don't have permissions to push my new branch to the repository. Should i also remove empty constructors under legacy folder?
